{
  pkgs,
  ...
}: let
  pkgs_ = with pkgs; [
    #glaxnimate
    #mediainfo
    #kdenlive
    #signal-desktop
    #alejandra
    #taplo
    #catppuccin-folders-mocha
    #super-tiny-icons
    #ncdu
    #imgcat
    #vlc
    #discord
    #streamlink
    #devenv
    #toybox
    tree-sitter
    #htop
    #bat
    xplr
    #yarn
    zsh
    #wget
    starship
    git
    #cargo
    exa
    #gnumake
    #direnv
    #stylua
    #shellcheck
    #deadnix
    #statix
    #plasma-vault
    #unzip
    #gocryptfs
    #luajitPackages.luacheck
    #sumneko-lua-language-server
    #python3
    #gcc
    #ffmpeg_5-full
    #haruna
    #llama-cpp-python
    #google-chrome
    #ouch
    #gitoxide
    #ix
    #timg
    #cmake
    #gh
    #discord
    #nitter
    #hdparm
    #havoc
    #tdesktop
    #openrgb
    #cabal-install
    #nodejs
    #twitch-tui
    #cm-rgb
    #gping
    #alpacka
    #tmux
    #qbittorrent
    #rqbit
    #radeontop
    #open3d
    #vlang
    #openboardview
    #wezterm
    #imgurbash2
    #ytcc
    #yt-dlp
    #ytmdl
    #flood
    #winetricks
    #haskellPackages.implicit-hie
    #haskellPackages.haskell-language-server
    #haskellPackages.hoogle
    #cabal-install
    #vulkan-tools
    #wine-staging
    #fuse-overlayfs
    #dwarfs
    #wine64
    #etcher
    #ckb-next
    #zenmonitor
    #radeontools
    #radeon-profile
    #stack
    #steam-run
    #steam-tui
    #steamcmd
  ];
  node = with pkgs.nodePackages; [
    #npm
  ];
  python_ = with pkgs.python39Packages; [
    #pip
  ];
  xorg_ = with pkgs.xorg; [
    # xrandr libX11 libXinerama
  ];
  pkgs__ = pkgs_ ++ node ++ python_;
in {
  home.packages =
    pkgs__;
}
