return {
	"nvzone/showkeys",
	cmd = "ShowkeysToggle",
	opts = {
		timeout = 1,
		maxkeys = 5,
		show_count = true,
		position = "top-center",
		winopts = {
			focusable = true,
			relative = "editor",
			style = "minimal",
			border = "single",
			height = 1,
			row = 1,
			col = 0,
			zindex = 100,
		},
		winhl = "FloatBorder:Comment,Normal:Normal",
		keyformat = {
			["<BS>"] = "󰁮 ",
			["<CR>"] = "󰘌",
			["<Space>"] = "󱁐",
			["<Up>"] = "󰁝",
			["<Down>"] = "󰁅",
			["<Left>"] = "󰁍",
			["<Right>"] = "󰁔",
			["<PageUp>"] = "Page 󰁝",
			["<PageDown>"] = "Page 󰁅",
			["<M>"] = "Alt",
			["<C>"] = "Ctrl",
		},
	},
}
