{
  pkgs,
  inputs,
  lib,
  enabled,
  ...
}: let
  inherit (inputs) systemd nix-ai-tools nixpkgs;
  pkgs_ = with pkgs; [
    wezterm
    gradle
    git
    pnpm
    rustc
    pkg-config
    glib
    gdk-pixbuf
    gdtoolkit_4
    #openwor
    jre
    statix
    #neovim
    ripgrep
    #pavucontrol
    blender
    #nixgl.auto.nixGLNvidiaBumblebee
    #nixgl.nixGLIntel
    riseup-vpn
    lutris
    libcamera
    fd
    vtsls
    biome
    kotlin-language-server
    kotlin-debug-adapter
    ktlint
    nixd
    warp-terminal
    fup-repl
    nil
    bun
    #kotlin-lsp
    #(btop.override { cudaSupport = true; })
    nvtopPackages.full
    libvdpau-va-gl
    intel-media-driver
    intel-gpu-tools
    intel-vaapi-driver
    #lunarvim
    #vlc
    nix-direnv
    devenv
    marksman
    nixd
    lenovo-legion
    pandoc
    w3m
    curl
    yarn
    tree-sitter
    #localsend
    #warp-terminal
    #input-remapper
    #systemd.packages.x86_64-linux.default
    luajitPackages.magick
    python313Packages.sixel
    python3
    dotenvhub
    hwinfo
    hwinfo-tui
    runal
    yatto
    signal-cli
    lua
    #crush
    sops
    #ollama
    #claude-code
    #glow
    #charm-freeze
    #pop
    #gopls
    gnumake
    cargo
    go
    #rustc
    gcc
    #ruff
    #basedpyright
    uv
    nodejs
    #lunarvim
    #devenv
    #direnv
    #nix-direnv
    #wezterm
    #gcc
    #yarn
    #pnpm
    #gnumake
    #cargo
    #nodejs
    #nodePackages.webtorrent-cli
    #dijo
    unzip
    #ripgrep
    #my-packge
    #glaxnimate
    #mediainfo
    #kdenlive
    #signal-desktop
    #alejandra
    #taplo
    #catppuccin-folders-mocha
    #super-tiny-icons
    #ncdu
    #imgcat
    #vlc
    #discord
    #streamlink
    #devenv
    #toybox
    #fd
    #tree-sitter
    #htop
    #bat
    #xplr
    #yarn
    #lazygit
    #wget
    #stylua
    #shellcheck
    #deadnix
    #statix
    #plasma-vault
    #unzip
    #gocryptfs
    #luajitPackages.luacheck
    #sumneko-lua-language-server
    #ffmpeg_5-full
    #haruna
    #llama-cpp-python
    #google-chrome
    #ouch
    #gitoxide
    #ix
    #timg
    #cmake
    #gh
    #discord
    #nitter
    #hdparm
    #havoc
    #tdesktop
    #openrgb
    #cabal-install
    #twitch-tui
    #cm-rgb
    #gping
    #alpacka
    #tmux
    #qbittorrent
    #rqbit
    #radeontop
    #open3d
    #vlang
    #openboardview
    #wezterm
    #imgurbash2
    #ytcc
    #yt-dlp
    #ytmdl
    #flood
    #motrix
    cage
    #sc-controller
    #python313Packages.ds4drv
    #winetricks
    #haskellPackages.implicit-hie
    #haskellPackages.haskell-language-server
    #haskellPackages.hoogle
    #cabal-install
    #vulkan-tools:wq
    #
    bottles
    #wineWowPackages.stable
    #fuse-overlayfs
    #nixfmt
    #dwarfs
    jq
    #moltengamepad
    hydralauncher
    #game-devices-udev-rules
    antimicrox
    #wine
    #winetricks
    #wine64Packages.waylandFull
    #etcher
    #ckb-next
    #zenmonitor
    #radeontools
    #radeon-profile
    #stack
    #steam-run
    #steam-tui
    #steamcmd
  ];
  nix-ai = with nix-ai-tools.packages.x86_64-linux; [
    #   crush
  ];
  node = with pkgs.nodePackages; [
    #npm
  ];
  python_ = with pkgs.python39Packages; [
    #pip
  ];
  xorg_ = with pkgs.xorg; [
    # xrandr libX11 libXinerama
  ];
  kotlin-lsp = inputs.kotlin-lsp.packages.x86_64-linux.default;
  pkgs__ = pkgs_ ++ node ++ python_ ++ nix-ai;
in {
  home = lib.mkIf enabled {
    home.packages = pkgs__;
  };
  nixos = lib.mkIf enabled {};
}
